name: Release

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - "v[0-9]+.*"
  workflow_dispatch:

jobs:
  release:
    uses: cargo-bins/cargo-dist/.github/workflows/release.yml@v0.30.2
